#pragma once

#include <FastLED.h>

#define HW_LEDS_PER_EAR 81
#define HW_NUM_RINGS 5
#define HW_RING_SIZE (uint8_t[]) {32,24,16,8,1}

#define HW_VIRTUAL_ROWS 17
#define HW_VIRTUAL_COLS 17

#define HW_CHIPSET WS2812B
#define HW_PIXEL_ORDER GRB

#define HW_LEFT_EAR_PIN D5
#define HW_RIGHT_EAR_PIN D4
#define HW_BUTTON_PIN D7
#define HW_VOLTAGE_PIN A0

#define HW_MAX_POWER_IN_MW 1000
#define HW_MAX_BRIGHTNESS 32
#define HW_VOLTAGE_CUTOFF 3.5

//
// Static mapping of ring pixels to virtual X/Y coordinates
// These were automatically generated by cartesian_ring_map.py
//
const uint8_t HW_V_COORDS_X[] = {
	8, 6, 5, 4, 2, 1, 1, 0, 0, 0, 1, 1, 2, 4, 5, 6, 8, 10, 11, 12, 14, 15, 15, 16, 16, 16, 15, 15, 14, 12, 11, 10,
	8, 6, 5, 4, 3, 2, 2, 2, 3, 4, 5, 6, 8, 10, 11, 12, 13, 14, 14, 14, 13, 12, 11, 10,
	8, 6, 5, 4, 4, 4, 5, 6, 8, 10, 11, 12, 12, 12, 11, 10,
	8, 7, 6, 7, 8, 9, 10, 9,
	8,
};
const uint8_t HW_V_COORDS_Y[] = {
	16, 16, 15, 15, 14, 12, 11, 10, 8, 6, 5, 4, 2, 1, 1, 0, 0, 0, 1, 1, 2, 4, 5, 6, 8, 10, 11, 12, 14, 15, 15, 16,
	14, 14, 13, 12, 11, 10, 8, 6, 5, 4, 3, 2, 2, 2, 3, 4, 5, 6, 8, 10, 11, 12, 13, 14,
	12, 12, 11, 10, 8, 6, 5, 4, 4, 4, 5, 6, 8, 10, 11, 12,
	10, 9, 8, 7, 6, 7, 8, 9,
	8,
};